# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.srcs/sources_1/ip/SPI_FIFO/SPI_FIFO.xci
# IP: The module: 'SPI_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.gen/sources_1/ip/SPI_FIFO/SPI_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_FIFO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.gen/sources_1/ip/SPI_FIFO/SPI_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.gen/sources_1/ip/SPI_FIFO/SPI_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.srcs/sources_1/ip/SPI_FIFO/SPI_FIFO.xci
# IP: The module: 'SPI_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.gen/sources_1/ip/SPI_FIFO/SPI_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.gen/sources_1/ip/SPI_FIFO/SPI_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nats/data/projects/Harbinger/HDL_v2/vivado_crap/harb_v2/harb_v2.gen/sources_1/ip/SPI_FIFO/SPI_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SPI_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
