/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QGroupBox *groupBox;
    QCheckBox *Out_0;
    QCheckBox *Out_1;
    QCheckBox *Out_2;
    QCheckBox *Out_3;
    QCheckBox *Out_4;
    QCheckBox *checkBox_6;
    QCheckBox *Out_5;
    QGroupBox *groupBox_2;
    QRadioButton *r_0_5;
    QRadioButton *r_1_5;
    QRadioButton *r_2_5;
    QRadioButton *r_3_5;
    QRadioButton *r_4_5;
    QRadioButton *r_5_5;
    QGroupBox *groupBox_3;
    QRadioButton *r_0_4;
    QRadioButton *r_1_4;
    QRadioButton *r_2_4;
    QRadioButton *r_3_4;
    QRadioButton *r_4_4;
    QRadioButton *r_5_4;
    QGroupBox *groupBox_4;
    QRadioButton *r_0_3;
    QRadioButton *r_1_3;
    QRadioButton *r_2_3;
    QRadioButton *r_3_3;
    QRadioButton *r_4_3;
    QRadioButton *r_5_3;
    QGroupBox *groupBox_5;
    QRadioButton *r_0_2;
    QRadioButton *r_1_2;
    QRadioButton *r_2_2;
    QRadioButton *r_3_2;
    QRadioButton *r_4_2;
    QRadioButton *r_5_2;
    QGroupBox *groupBox_6;
    QRadioButton *r_0_1;
    QRadioButton *r_1_1;
    QRadioButton *r_2_1;
    QRadioButton *r_3_1;
    QRadioButton *r_4_1;
    QRadioButton *r_5_1;
    QGroupBox *groupBox_7;
    QRadioButton *r_0_0;
    QRadioButton *r_1_0;
    QRadioButton *r_2_0;
    QRadioButton *r_3_0;
    QRadioButton *r_4_0;
    QRadioButton *r_5_0;
    QPushButton *pbGenerate;
    QPlainTextEdit *txtPatch;
    QTabWidget *tabWidget;
    QWidget *op0_tab;
    QLineEdit *txt_op_0_FRatio;
    QLabel *label;
    QLineEdit *txt_op_0_Att_time;
    QLabel *label_2;
    QLineEdit *txt_op_0_Att_Amp;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *txt_op_0_Decay_time;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *txt_op_0_sus_lvl;
    QLineEdit *txt_op_0_sus_time;
    QLabel *label_8;
    QLineEdit *txt_op_0_re_time;
    QCheckBox *op0_cb_fixamp;
    QWidget *tab_2;
    QLineEdit *txt_op_1_sus_lvl_2;
    QLineEdit *txt_op_1_sus_time_2;
    QLabel *label_5;
    QLabel *label_9;
    QLineEdit *txt_op_1_Decay_time_2;
    QLineEdit *txt_op_1_FRatio;
    QLabel *label_10;
    QLineEdit *txt_op_1_Att_time;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *txt_op_1_Att_Amp;
    QLineEdit *txt_op_1_re_time_2;
    QCheckBox *op1_cb_fixamp;
    QLabel *label_13;
    QLabel *label_14;
    QWidget *tab;
    QLineEdit *txt_op_1_sus_lvl_3;
    QLabel *label_15;
    QLineEdit *txt_op_1_sus_time_3;
    QLineEdit *txt_op_1_Decay_time_3;
    QCheckBox *op2_cb_fixamp;
    QLabel *label_16;
    QLineEdit *txt_op_2_Att_time;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *txt_op_2_Att_Amp;
    QLineEdit *txt_op_2_FRatio;
    QLabel *label_19;
    QLineEdit *txt_op_1_re_time_3;
    QLabel *label_20;
    QLabel *label_21;
    QWidget *tab_3;
    QLineEdit *txt_op_1_sus_lvl_4;
    QLabel *label_22;
    QLineEdit *txt_op_1_sus_time_4;
    QLineEdit *txt_op_1_Decay_time_4;
    QCheckBox *op3_cb_fixamp;
    QLabel *label_23;
    QLineEdit *txt_op_3_Att_time;
    QLabel *label_24;
    QLabel *label_25;
    QLineEdit *txt_op_3_Att_Amp;
    QLineEdit *txt_op_3_FRatio;
    QLabel *label_26;
    QLineEdit *txt_op_1_re_time_4;
    QLabel *label_27;
    QLabel *label_28;
    QWidget *tab_4;
    QLineEdit *txt_op_1_sus_lvl_5;
    QLabel *label_29;
    QLineEdit *txt_op_1_sus_time_5;
    QLineEdit *txt_op_1_Decay_time_5;
    QCheckBox *op4_cb_fixamp;
    QLabel *label_30;
    QLineEdit *txt_op_4_Att_time;
    QLabel *label_31;
    QLabel *label_32;
    QLineEdit *txt_op_4_Att_Amp;
    QLineEdit *txt_op_4_FRatio;
    QLabel *label_33;
    QLineEdit *txt_op_1_re_time_5;
    QLabel *label_34;
    QLabel *label_35;
    QWidget *tab_5;
    QLineEdit *txt_op_1_sus_lvl_6;
    QLabel *label_36;
    QLineEdit *txt_op_1_sus_time_6;
    QLineEdit *txt_op_1_Decay_time_6;
    QCheckBox *op5_cb_fixamp;
    QLabel *label_37;
    QLineEdit *txt_op_5_Att_time;
    QLabel *label_38;
    QLabel *label_39;
    QLineEdit *txt_op_5_Att_Amp;
    QLineEdit *txt_op_5_FRatio;
    QLabel *label_40;
    QLineEdit *txt_op_1_re_time_6;
    QLabel *label_41;
    QLabel *label_42;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(893, 830);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(609, 0, 81, 181));
        Out_0 = new QCheckBox(groupBox);
        Out_0->setObjectName(QString::fromUtf8("Out_0"));
        Out_0->setGeometry(QRect(30, 30, 21, 22));
        Out_1 = new QCheckBox(groupBox);
        Out_1->setObjectName(QString::fromUtf8("Out_1"));
        Out_1->setGeometry(QRect(30, 50, 21, 22));
        Out_2 = new QCheckBox(groupBox);
        Out_2->setObjectName(QString::fromUtf8("Out_2"));
        Out_2->setGeometry(QRect(30, 70, 21, 22));
        Out_3 = new QCheckBox(groupBox);
        Out_3->setObjectName(QString::fromUtf8("Out_3"));
        Out_3->setGeometry(QRect(30, 90, 21, 22));
        Out_4 = new QCheckBox(groupBox);
        Out_4->setObjectName(QString::fromUtf8("Out_4"));
        Out_4->setGeometry(QRect(30, 110, 21, 22));
        checkBox_6 = new QCheckBox(groupBox);
        checkBox_6->setObjectName(QString::fromUtf8("checkBox_6"));
        checkBox_6->setGeometry(QRect(40, 180, 21, 22));
        Out_5 = new QCheckBox(groupBox);
        Out_5->setObjectName(QString::fromUtf8("Out_5"));
        Out_5->setGeometry(QRect(30, 130, 21, 22));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(510, 0, 81, 181));
        r_0_5 = new QRadioButton(groupBox_2);
        r_0_5->setObjectName(QString::fromUtf8("r_0_5"));
        r_0_5->setGeometry(QRect(30, 40, 21, 21));
        r_1_5 = new QRadioButton(groupBox_2);
        r_1_5->setObjectName(QString::fromUtf8("r_1_5"));
        r_1_5->setGeometry(QRect(30, 60, 21, 21));
        r_2_5 = new QRadioButton(groupBox_2);
        r_2_5->setObjectName(QString::fromUtf8("r_2_5"));
        r_2_5->setGeometry(QRect(30, 80, 21, 21));
        r_3_5 = new QRadioButton(groupBox_2);
        r_3_5->setObjectName(QString::fromUtf8("r_3_5"));
        r_3_5->setGeometry(QRect(30, 100, 21, 21));
        r_4_5 = new QRadioButton(groupBox_2);
        r_4_5->setObjectName(QString::fromUtf8("r_4_5"));
        r_4_5->setGeometry(QRect(30, 120, 21, 21));
        r_5_5 = new QRadioButton(groupBox_2);
        r_5_5->setObjectName(QString::fromUtf8("r_5_5"));
        r_5_5->setGeometry(QRect(30, 140, 21, 21));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(420, 0, 81, 181));
        r_0_4 = new QRadioButton(groupBox_3);
        r_0_4->setObjectName(QString::fromUtf8("r_0_4"));
        r_0_4->setGeometry(QRect(30, 40, 21, 21));
        r_1_4 = new QRadioButton(groupBox_3);
        r_1_4->setObjectName(QString::fromUtf8("r_1_4"));
        r_1_4->setGeometry(QRect(30, 60, 21, 21));
        r_2_4 = new QRadioButton(groupBox_3);
        r_2_4->setObjectName(QString::fromUtf8("r_2_4"));
        r_2_4->setGeometry(QRect(30, 80, 21, 21));
        r_3_4 = new QRadioButton(groupBox_3);
        r_3_4->setObjectName(QString::fromUtf8("r_3_4"));
        r_3_4->setGeometry(QRect(30, 100, 21, 21));
        r_4_4 = new QRadioButton(groupBox_3);
        r_4_4->setObjectName(QString::fromUtf8("r_4_4"));
        r_4_4->setGeometry(QRect(30, 120, 21, 21));
        r_5_4 = new QRadioButton(groupBox_3);
        r_5_4->setObjectName(QString::fromUtf8("r_5_4"));
        r_5_4->setGeometry(QRect(30, 140, 21, 21));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(330, 0, 81, 181));
        r_0_3 = new QRadioButton(groupBox_4);
        r_0_3->setObjectName(QString::fromUtf8("r_0_3"));
        r_0_3->setGeometry(QRect(30, 40, 21, 21));
        r_1_3 = new QRadioButton(groupBox_4);
        r_1_3->setObjectName(QString::fromUtf8("r_1_3"));
        r_1_3->setGeometry(QRect(30, 60, 21, 21));
        r_2_3 = new QRadioButton(groupBox_4);
        r_2_3->setObjectName(QString::fromUtf8("r_2_3"));
        r_2_3->setGeometry(QRect(30, 80, 21, 21));
        r_3_3 = new QRadioButton(groupBox_4);
        r_3_3->setObjectName(QString::fromUtf8("r_3_3"));
        r_3_3->setGeometry(QRect(30, 100, 21, 21));
        r_4_3 = new QRadioButton(groupBox_4);
        r_4_3->setObjectName(QString::fromUtf8("r_4_3"));
        r_4_3->setGeometry(QRect(30, 120, 21, 21));
        r_5_3 = new QRadioButton(groupBox_4);
        r_5_3->setObjectName(QString::fromUtf8("r_5_3"));
        r_5_3->setGeometry(QRect(30, 140, 21, 21));
        groupBox_5 = new QGroupBox(centralwidget);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(240, 0, 81, 181));
        r_0_2 = new QRadioButton(groupBox_5);
        r_0_2->setObjectName(QString::fromUtf8("r_0_2"));
        r_0_2->setGeometry(QRect(30, 40, 21, 21));
        r_1_2 = new QRadioButton(groupBox_5);
        r_1_2->setObjectName(QString::fromUtf8("r_1_2"));
        r_1_2->setGeometry(QRect(30, 60, 21, 21));
        r_2_2 = new QRadioButton(groupBox_5);
        r_2_2->setObjectName(QString::fromUtf8("r_2_2"));
        r_2_2->setGeometry(QRect(30, 80, 21, 21));
        r_3_2 = new QRadioButton(groupBox_5);
        r_3_2->setObjectName(QString::fromUtf8("r_3_2"));
        r_3_2->setGeometry(QRect(30, 100, 21, 21));
        r_4_2 = new QRadioButton(groupBox_5);
        r_4_2->setObjectName(QString::fromUtf8("r_4_2"));
        r_4_2->setGeometry(QRect(30, 120, 21, 21));
        r_5_2 = new QRadioButton(groupBox_5);
        r_5_2->setObjectName(QString::fromUtf8("r_5_2"));
        r_5_2->setGeometry(QRect(30, 140, 21, 21));
        groupBox_6 = new QGroupBox(centralwidget);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(150, 0, 81, 181));
        r_0_1 = new QRadioButton(groupBox_6);
        r_0_1->setObjectName(QString::fromUtf8("r_0_1"));
        r_0_1->setGeometry(QRect(30, 40, 21, 21));
        r_1_1 = new QRadioButton(groupBox_6);
        r_1_1->setObjectName(QString::fromUtf8("r_1_1"));
        r_1_1->setGeometry(QRect(30, 60, 21, 21));
        r_2_1 = new QRadioButton(groupBox_6);
        r_2_1->setObjectName(QString::fromUtf8("r_2_1"));
        r_2_1->setGeometry(QRect(30, 80, 21, 21));
        r_3_1 = new QRadioButton(groupBox_6);
        r_3_1->setObjectName(QString::fromUtf8("r_3_1"));
        r_3_1->setGeometry(QRect(30, 100, 21, 21));
        r_4_1 = new QRadioButton(groupBox_6);
        r_4_1->setObjectName(QString::fromUtf8("r_4_1"));
        r_4_1->setGeometry(QRect(30, 120, 21, 21));
        r_5_1 = new QRadioButton(groupBox_6);
        r_5_1->setObjectName(QString::fromUtf8("r_5_1"));
        r_5_1->setGeometry(QRect(30, 140, 21, 21));
        groupBox_7 = new QGroupBox(centralwidget);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(60, 0, 81, 181));
        r_0_0 = new QRadioButton(groupBox_7);
        r_0_0->setObjectName(QString::fromUtf8("r_0_0"));
        r_0_0->setGeometry(QRect(30, 40, 21, 21));
        r_1_0 = new QRadioButton(groupBox_7);
        r_1_0->setObjectName(QString::fromUtf8("r_1_0"));
        r_1_0->setGeometry(QRect(30, 60, 21, 21));
        r_2_0 = new QRadioButton(groupBox_7);
        r_2_0->setObjectName(QString::fromUtf8("r_2_0"));
        r_2_0->setGeometry(QRect(30, 80, 21, 21));
        r_3_0 = new QRadioButton(groupBox_7);
        r_3_0->setObjectName(QString::fromUtf8("r_3_0"));
        r_3_0->setGeometry(QRect(30, 100, 21, 21));
        r_4_0 = new QRadioButton(groupBox_7);
        r_4_0->setObjectName(QString::fromUtf8("r_4_0"));
        r_4_0->setGeometry(QRect(30, 120, 21, 21));
        r_5_0 = new QRadioButton(groupBox_7);
        r_5_0->setObjectName(QString::fromUtf8("r_5_0"));
        r_5_0->setGeometry(QRect(30, 140, 21, 21));
        pbGenerate = new QPushButton(centralwidget);
        pbGenerate->setObjectName(QString::fromUtf8("pbGenerate"));
        pbGenerate->setGeometry(QRect(780, 730, 88, 34));
        txtPatch = new QPlainTextEdit(centralwidget);
        txtPatch->setObjectName(QString::fromUtf8("txtPatch"));
        txtPatch->setGeometry(QRect(620, 190, 251, 531));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(10, 200, 591, 521));
        op0_tab = new QWidget();
        op0_tab->setObjectName(QString::fromUtf8("op0_tab"));
        txt_op_0_FRatio = new QLineEdit(op0_tab);
        txt_op_0_FRatio->setObjectName(QString::fromUtf8("txt_op_0_FRatio"));
        txt_op_0_FRatio->setGeometry(QRect(160, 20, 113, 32));
        label = new QLabel(op0_tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 30, 81, 18));
        txt_op_0_Att_time = new QLineEdit(op0_tab);
        txt_op_0_Att_time->setObjectName(QString::fromUtf8("txt_op_0_Att_time"));
        txt_op_0_Att_time->setGeometry(QRect(160, 80, 113, 32));
        label_2 = new QLabel(op0_tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 90, 81, 18));
        txt_op_0_Att_Amp = new QLineEdit(op0_tab);
        txt_op_0_Att_Amp->setObjectName(QString::fromUtf8("txt_op_0_Att_Amp"));
        txt_op_0_Att_Amp->setGeometry(QRect(160, 120, 113, 32));
        label_3 = new QLabel(op0_tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 130, 131, 18));
        label_4 = new QLabel(op0_tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 180, 81, 18));
        txt_op_0_Decay_time = new QLineEdit(op0_tab);
        txt_op_0_Decay_time->setObjectName(QString::fromUtf8("txt_op_0_Decay_time"));
        txt_op_0_Decay_time->setGeometry(QRect(160, 170, 113, 32));
        label_6 = new QLabel(op0_tab);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 220, 81, 18));
        label_7 = new QLabel(op0_tab);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 260, 131, 18));
        txt_op_0_sus_lvl = new QLineEdit(op0_tab);
        txt_op_0_sus_lvl->setObjectName(QString::fromUtf8("txt_op_0_sus_lvl"));
        txt_op_0_sus_lvl->setGeometry(QRect(160, 210, 113, 32));
        txt_op_0_sus_time = new QLineEdit(op0_tab);
        txt_op_0_sus_time->setObjectName(QString::fromUtf8("txt_op_0_sus_time"));
        txt_op_0_sus_time->setGeometry(QRect(160, 250, 113, 32));
        label_8 = new QLabel(op0_tab);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 300, 81, 18));
        txt_op_0_re_time = new QLineEdit(op0_tab);
        txt_op_0_re_time->setObjectName(QString::fromUtf8("txt_op_0_re_time"));
        txt_op_0_re_time->setGeometry(QRect(160, 290, 113, 32));
        op0_cb_fixamp = new QCheckBox(op0_tab);
        op0_cb_fixamp->setObjectName(QString::fromUtf8("op0_cb_fixamp"));
        op0_cb_fixamp->setGeometry(QRect(290, 130, 88, 22));
        tabWidget->addTab(op0_tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        txt_op_1_sus_lvl_2 = new QLineEdit(tab_2);
        txt_op_1_sus_lvl_2->setObjectName(QString::fromUtf8("txt_op_1_sus_lvl_2"));
        txt_op_1_sus_lvl_2->setGeometry(QRect(160, 220, 113, 32));
        txt_op_1_sus_time_2 = new QLineEdit(tab_2);
        txt_op_1_sus_time_2->setObjectName(QString::fromUtf8("txt_op_1_sus_time_2"));
        txt_op_1_sus_time_2->setGeometry(QRect(160, 260, 113, 32));
        label_5 = new QLabel(tab_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 190, 81, 18));
        label_9 = new QLabel(tab_2);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(10, 40, 81, 18));
        txt_op_1_Decay_time_2 = new QLineEdit(tab_2);
        txt_op_1_Decay_time_2->setObjectName(QString::fromUtf8("txt_op_1_Decay_time_2"));
        txt_op_1_Decay_time_2->setGeometry(QRect(160, 180, 113, 32));
        txt_op_1_FRatio = new QLineEdit(tab_2);
        txt_op_1_FRatio->setObjectName(QString::fromUtf8("txt_op_1_FRatio"));
        txt_op_1_FRatio->setGeometry(QRect(160, 30, 113, 32));
        label_10 = new QLabel(tab_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 270, 131, 18));
        txt_op_1_Att_time = new QLineEdit(tab_2);
        txt_op_1_Att_time->setObjectName(QString::fromUtf8("txt_op_1_Att_time"));
        txt_op_1_Att_time->setGeometry(QRect(160, 90, 113, 32));
        label_11 = new QLabel(tab_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 140, 131, 18));
        label_12 = new QLabel(tab_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 230, 81, 18));
        txt_op_1_Att_Amp = new QLineEdit(tab_2);
        txt_op_1_Att_Amp->setObjectName(QString::fromUtf8("txt_op_1_Att_Amp"));
        txt_op_1_Att_Amp->setGeometry(QRect(160, 130, 113, 32));
        txt_op_1_re_time_2 = new QLineEdit(tab_2);
        txt_op_1_re_time_2->setObjectName(QString::fromUtf8("txt_op_1_re_time_2"));
        txt_op_1_re_time_2->setGeometry(QRect(160, 300, 113, 32));
        op1_cb_fixamp = new QCheckBox(tab_2);
        op1_cb_fixamp->setObjectName(QString::fromUtf8("op1_cb_fixamp"));
        op1_cb_fixamp->setGeometry(QRect(290, 140, 88, 22));
        label_13 = new QLabel(tab_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 310, 81, 18));
        label_14 = new QLabel(tab_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 100, 81, 18));
        tabWidget->addTab(tab_2, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        txt_op_1_sus_lvl_3 = new QLineEdit(tab);
        txt_op_1_sus_lvl_3->setObjectName(QString::fromUtf8("txt_op_1_sus_lvl_3"));
        txt_op_1_sus_lvl_3->setGeometry(QRect(170, 220, 113, 32));
        label_15 = new QLabel(tab);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(20, 270, 131, 18));
        txt_op_1_sus_time_3 = new QLineEdit(tab);
        txt_op_1_sus_time_3->setObjectName(QString::fromUtf8("txt_op_1_sus_time_3"));
        txt_op_1_sus_time_3->setGeometry(QRect(170, 260, 113, 32));
        txt_op_1_Decay_time_3 = new QLineEdit(tab);
        txt_op_1_Decay_time_3->setObjectName(QString::fromUtf8("txt_op_1_Decay_time_3"));
        txt_op_1_Decay_time_3->setGeometry(QRect(170, 180, 113, 32));
        op2_cb_fixamp = new QCheckBox(tab);
        op2_cb_fixamp->setObjectName(QString::fromUtf8("op2_cb_fixamp"));
        op2_cb_fixamp->setGeometry(QRect(300, 140, 88, 22));
        label_16 = new QLabel(tab);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(20, 230, 81, 18));
        txt_op_2_Att_time = new QLineEdit(tab);
        txt_op_2_Att_time->setObjectName(QString::fromUtf8("txt_op_2_Att_time"));
        txt_op_2_Att_time->setGeometry(QRect(170, 90, 113, 32));
        label_17 = new QLabel(tab);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(20, 140, 131, 18));
        label_18 = new QLabel(tab);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(20, 100, 81, 18));
        txt_op_2_Att_Amp = new QLineEdit(tab);
        txt_op_2_Att_Amp->setObjectName(QString::fromUtf8("txt_op_2_Att_Amp"));
        txt_op_2_Att_Amp->setGeometry(QRect(170, 130, 113, 32));
        txt_op_2_FRatio = new QLineEdit(tab);
        txt_op_2_FRatio->setObjectName(QString::fromUtf8("txt_op_2_FRatio"));
        txt_op_2_FRatio->setGeometry(QRect(170, 30, 113, 32));
        label_19 = new QLabel(tab);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(20, 190, 81, 18));
        txt_op_1_re_time_3 = new QLineEdit(tab);
        txt_op_1_re_time_3->setObjectName(QString::fromUtf8("txt_op_1_re_time_3"));
        txt_op_1_re_time_3->setGeometry(QRect(170, 300, 113, 32));
        label_20 = new QLabel(tab);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(20, 40, 81, 18));
        label_21 = new QLabel(tab);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 310, 81, 18));
        tabWidget->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        txt_op_1_sus_lvl_4 = new QLineEdit(tab_3);
        txt_op_1_sus_lvl_4->setObjectName(QString::fromUtf8("txt_op_1_sus_lvl_4"));
        txt_op_1_sus_lvl_4->setGeometry(QRect(190, 230, 113, 32));
        label_22 = new QLabel(tab_3);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(40, 280, 131, 18));
        txt_op_1_sus_time_4 = new QLineEdit(tab_3);
        txt_op_1_sus_time_4->setObjectName(QString::fromUtf8("txt_op_1_sus_time_4"));
        txt_op_1_sus_time_4->setGeometry(QRect(190, 270, 113, 32));
        txt_op_1_Decay_time_4 = new QLineEdit(tab_3);
        txt_op_1_Decay_time_4->setObjectName(QString::fromUtf8("txt_op_1_Decay_time_4"));
        txt_op_1_Decay_time_4->setGeometry(QRect(190, 190, 113, 32));
        op3_cb_fixamp = new QCheckBox(tab_3);
        op3_cb_fixamp->setObjectName(QString::fromUtf8("op3_cb_fixamp"));
        op3_cb_fixamp->setGeometry(QRect(320, 150, 88, 22));
        label_23 = new QLabel(tab_3);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(40, 240, 81, 18));
        txt_op_3_Att_time = new QLineEdit(tab_3);
        txt_op_3_Att_time->setObjectName(QString::fromUtf8("txt_op_3_Att_time"));
        txt_op_3_Att_time->setGeometry(QRect(190, 100, 113, 32));
        label_24 = new QLabel(tab_3);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(40, 150, 131, 18));
        label_25 = new QLabel(tab_3);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(40, 110, 81, 18));
        txt_op_3_Att_Amp = new QLineEdit(tab_3);
        txt_op_3_Att_Amp->setObjectName(QString::fromUtf8("txt_op_3_Att_Amp"));
        txt_op_3_Att_Amp->setGeometry(QRect(190, 140, 113, 32));
        txt_op_3_FRatio = new QLineEdit(tab_3);
        txt_op_3_FRatio->setObjectName(QString::fromUtf8("txt_op_3_FRatio"));
        txt_op_3_FRatio->setGeometry(QRect(190, 40, 113, 32));
        label_26 = new QLabel(tab_3);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(40, 200, 81, 18));
        txt_op_1_re_time_4 = new QLineEdit(tab_3);
        txt_op_1_re_time_4->setObjectName(QString::fromUtf8("txt_op_1_re_time_4"));
        txt_op_1_re_time_4->setGeometry(QRect(190, 310, 113, 32));
        label_27 = new QLabel(tab_3);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(40, 50, 81, 18));
        label_28 = new QLabel(tab_3);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(40, 320, 81, 18));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        txt_op_1_sus_lvl_5 = new QLineEdit(tab_4);
        txt_op_1_sus_lvl_5->setObjectName(QString::fromUtf8("txt_op_1_sus_lvl_5"));
        txt_op_1_sus_lvl_5->setGeometry(QRect(180, 220, 113, 32));
        label_29 = new QLabel(tab_4);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(30, 270, 131, 18));
        txt_op_1_sus_time_5 = new QLineEdit(tab_4);
        txt_op_1_sus_time_5->setObjectName(QString::fromUtf8("txt_op_1_sus_time_5"));
        txt_op_1_sus_time_5->setGeometry(QRect(180, 260, 113, 32));
        txt_op_1_Decay_time_5 = new QLineEdit(tab_4);
        txt_op_1_Decay_time_5->setObjectName(QString::fromUtf8("txt_op_1_Decay_time_5"));
        txt_op_1_Decay_time_5->setGeometry(QRect(180, 180, 113, 32));
        op4_cb_fixamp = new QCheckBox(tab_4);
        op4_cb_fixamp->setObjectName(QString::fromUtf8("op4_cb_fixamp"));
        op4_cb_fixamp->setGeometry(QRect(310, 140, 88, 22));
        label_30 = new QLabel(tab_4);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(30, 230, 81, 18));
        txt_op_4_Att_time = new QLineEdit(tab_4);
        txt_op_4_Att_time->setObjectName(QString::fromUtf8("txt_op_4_Att_time"));
        txt_op_4_Att_time->setGeometry(QRect(180, 90, 113, 32));
        label_31 = new QLabel(tab_4);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(30, 140, 131, 18));
        label_32 = new QLabel(tab_4);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(30, 100, 81, 18));
        txt_op_4_Att_Amp = new QLineEdit(tab_4);
        txt_op_4_Att_Amp->setObjectName(QString::fromUtf8("txt_op_4_Att_Amp"));
        txt_op_4_Att_Amp->setGeometry(QRect(180, 130, 113, 32));
        txt_op_4_FRatio = new QLineEdit(tab_4);
        txt_op_4_FRatio->setObjectName(QString::fromUtf8("txt_op_4_FRatio"));
        txt_op_4_FRatio->setGeometry(QRect(180, 30, 113, 32));
        label_33 = new QLabel(tab_4);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(30, 190, 81, 18));
        txt_op_1_re_time_5 = new QLineEdit(tab_4);
        txt_op_1_re_time_5->setObjectName(QString::fromUtf8("txt_op_1_re_time_5"));
        txt_op_1_re_time_5->setGeometry(QRect(180, 300, 113, 32));
        label_34 = new QLabel(tab_4);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(30, 40, 81, 18));
        label_35 = new QLabel(tab_4);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(30, 310, 81, 18));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        txt_op_1_sus_lvl_6 = new QLineEdit(tab_5);
        txt_op_1_sus_lvl_6->setObjectName(QString::fromUtf8("txt_op_1_sus_lvl_6"));
        txt_op_1_sus_lvl_6->setGeometry(QRect(190, 230, 113, 32));
        label_36 = new QLabel(tab_5);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(40, 280, 131, 18));
        txt_op_1_sus_time_6 = new QLineEdit(tab_5);
        txt_op_1_sus_time_6->setObjectName(QString::fromUtf8("txt_op_1_sus_time_6"));
        txt_op_1_sus_time_6->setGeometry(QRect(190, 270, 113, 32));
        txt_op_1_Decay_time_6 = new QLineEdit(tab_5);
        txt_op_1_Decay_time_6->setObjectName(QString::fromUtf8("txt_op_1_Decay_time_6"));
        txt_op_1_Decay_time_6->setGeometry(QRect(190, 190, 113, 32));
        op5_cb_fixamp = new QCheckBox(tab_5);
        op5_cb_fixamp->setObjectName(QString::fromUtf8("op5_cb_fixamp"));
        op5_cb_fixamp->setGeometry(QRect(320, 150, 88, 22));
        label_37 = new QLabel(tab_5);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(40, 240, 81, 18));
        txt_op_5_Att_time = new QLineEdit(tab_5);
        txt_op_5_Att_time->setObjectName(QString::fromUtf8("txt_op_5_Att_time"));
        txt_op_5_Att_time->setGeometry(QRect(190, 100, 113, 32));
        label_38 = new QLabel(tab_5);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(40, 150, 131, 18));
        label_39 = new QLabel(tab_5);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(40, 110, 81, 18));
        txt_op_5_Att_Amp = new QLineEdit(tab_5);
        txt_op_5_Att_Amp->setObjectName(QString::fromUtf8("txt_op_5_Att_Amp"));
        txt_op_5_Att_Amp->setGeometry(QRect(190, 140, 113, 32));
        txt_op_5_FRatio = new QLineEdit(tab_5);
        txt_op_5_FRatio->setObjectName(QString::fromUtf8("txt_op_5_FRatio"));
        txt_op_5_FRatio->setGeometry(QRect(190, 40, 113, 32));
        label_40 = new QLabel(tab_5);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(40, 200, 81, 18));
        txt_op_1_re_time_6 = new QLineEdit(tab_5);
        txt_op_1_re_time_6->setObjectName(QString::fromUtf8("txt_op_1_re_time_6"));
        txt_op_1_re_time_6->setGeometry(QRect(190, 310, 113, 32));
        label_41 = new QLabel(tab_5);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(40, 50, 81, 18));
        label_42 = new QLabel(tab_5);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(40, 320, 81, 18));
        tabWidget->addTab(tab_5, QString());
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 893, 30));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindow", "Output", nullptr));
        Out_0->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        Out_1->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        Out_2->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        Out_3->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        Out_4->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        checkBox_6->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        Out_5->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("MainWindow", "5", nullptr));
        r_0_5->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_1_5->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_2_5->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_3_5->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_4_5->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_5_5->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindow", "4", nullptr));
        r_0_4->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_1_4->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_2_4->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_3_4->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_4_4->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_5_4->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "3", nullptr));
        r_0_3->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_1_3->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_2_3->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_3_3->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_4_3->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_5_3->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWindow", "2", nullptr));
        r_0_2->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_1_2->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_2_2->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_3_2->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_4_2->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_5_2->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("MainWindow", "1", nullptr));
        r_0_1->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_1_1->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_2_1->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_3_1->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_4_1->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_5_1->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("MainWindow", "0", nullptr));
        r_0_0->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_1_0->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_2_0->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_3_0->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_4_0->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        r_5_0->setText(QCoreApplication::translate("MainWindow", "RadioButton", nullptr));
        pbGenerate->setText(QCoreApplication::translate("MainWindow", "Generate", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Freq Ratio", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Attack time", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Attack max amplitude", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Decay Time", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Sustain level", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Sustain Time", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Release Time", nullptr));
        op0_cb_fixamp->setText(QCoreApplication::translate("MainWindow", "FixAmp", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(op0_tab), QCoreApplication::translate("MainWindow", "Op 0", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Decay Time", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Freq Ratio", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Sustain Time", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Attack max amplitude", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Sustain level", nullptr));
        op1_cb_fixamp->setText(QCoreApplication::translate("MainWindow", "FixAmp", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Release Time", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Attack time", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "Op 1", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Sustain Time", nullptr));
        op2_cb_fixamp->setText(QCoreApplication::translate("MainWindow", "FixAmp", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Sustain level", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Attack max amplitude", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Attack time", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Decay Time", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Freq Ratio", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Release Time", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "Op 2", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "Sustain Time", nullptr));
        op3_cb_fixamp->setText(QCoreApplication::translate("MainWindow", "FixAmp", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Sustain level", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Attack max amplitude", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Attack time", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Decay Time", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Freq Ratio", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Release Time", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("MainWindow", "Op 3", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Sustain Time", nullptr));
        op4_cb_fixamp->setText(QCoreApplication::translate("MainWindow", "FixAmp", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "Sustain level", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "Attack max amplitude", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "Attack time", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "Decay Time", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Freq Ratio", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Release Time", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QCoreApplication::translate("MainWindow", "Op 4", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Sustain Time", nullptr));
        op5_cb_fixamp->setText(QCoreApplication::translate("MainWindow", "FixAmp", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Sustain level", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "Attack max amplitude", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Attack time", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "Decay Time", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Freq Ratio", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "Release Time", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QCoreApplication::translate("MainWindow", "Op 5", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
