# set default build target for rp2040
[build]
target = "thumbv6m-none-eabi"
 
runner = "probe-run --chip RP2040"
 
# use appropriate memory layout
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]
