set_property PACKAGE_PIN A2 [get_ports {leds[7]}]
set_property PACKAGE_PIN B2 [get_ports {leds[6]}]
set_property PACKAGE_PIN B1 [get_ports {leds[5]}]
set_property PACKAGE_PIN C1 [get_ports {leds[4]}]
set_property PACKAGE_PIN B3 [get_ports {leds[3]}]
set_property PACKAGE_PIN B4 [get_ports {leds[2]}]
set_property PACKAGE_PIN A3 [get_ports {leds[1]}]
set_property PACKAGE_PIN A4 [get_ports {leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property DRIVE 12 [get_ports {leds[7]}]
set_property DRIVE 12 [get_ports {leds[6]}]
set_property DRIVE 12 [get_ports {leds[5]}]
set_property DRIVE 12 [get_ports {leds[4]}]
set_property DRIVE 12 [get_ports {leds[3]}]
set_property DRIVE 12 [get_ports {leds[2]}]
set_property DRIVE 12 [get_ports {leds[1]}]
set_property DRIVE 12 [get_ports {leds[0]}]
set_property PACKAGE_PIN K14 [get_ports mck]
set_property IOSTANDARD LVCMOS33 [get_ports mck]
set_property SLEW FAST [get_ports mck]
set_property PACKAGE_PIN J15 [get_ports lrck]
set_property IOSTANDARD LVCMOS33 [get_ports lrck]
set_property SLEW FAST [get_ports lrck]
set_property PACKAGE_PIN L13 [get_ports sck]
set_property IOSTANDARD LVCMOS33 [get_ports sck]
set_property SLEW FAST [get_ports sck]
set_property PACKAGE_PIN M13 [get_ports sd]
set_property IOSTANDARD LVCMOS33 [get_ports sd]
set_property SLEW FAST [get_ports sd]
set_property PACKAGE_PIN L15 [get_ports midi_in]
set_property IOSTANDARD LVCMOS33 [get_ports midi_in]

set_property PACKAGE_PIN N15 [get_ports sck_in]
set_property IOSTANDARD LVCMOS33 [get_ports sck_in]
set_property PACKAGE_PIN N13 [get_ports cs_in]
set_property IOSTANDARD LVCMOS33 [get_ports cs_in]
set_property PACKAGE_PIN P14 [get_ports mosi0_in]
set_property IOSTANDARD LVCMOS33 [get_ports mosi0_in]
set_property PACKAGE_PIN N1 [get_ports mosi1_in]
set_property IOSTANDARD LVCMOS33 [get_ports mosi1_in]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sck_in_IBUF]

create_clock -period 32.000 -name sck_in -add [get_ports sck_in]


set_property PACKAGE_PIN F2 [get_ports {RGBLEDS[2]}]
set_property PACKAGE_PIN D3 [get_ports {RGBLEDS[1]}]
set_property PACKAGE_PIN F1 [get_ports {RGBLEDS[0]}]
set_property PACKAGE_PIN E1 [get_ports {ILED[3]}]
set_property PACKAGE_PIN J1 [get_ports {ILED[2]}]
set_property PACKAGE_PIN K1 [get_ports {ILED[1]}]
set_property PACKAGE_PIN E2 [get_ports {ILED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ILED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ILED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ILED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ILED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGBLEDS[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGBLEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGBLEDS[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN M9 [get_ports clk]

set_property OFFCHIP_TERM NONE [get_ports lrck]
set_property OFFCHIP_TERM NONE [get_ports mck]
set_property OFFCHIP_TERM NONE [get_ports sck]
set_property OFFCHIP_TERM NONE [get_ports sd]
set_property OFFCHIP_TERM NONE [get_ports leds[7]]
set_property OFFCHIP_TERM NONE [get_ports leds[6]]
set_property OFFCHIP_TERM NONE [get_ports leds[5]]
set_property OFFCHIP_TERM NONE [get_ports leds[4]]
set_property OFFCHIP_TERM NONE [get_ports leds[3]]
set_property OFFCHIP_TERM NONE [get_ports leds[2]]
set_property OFFCHIP_TERM NONE [get_ports leds[1]]
set_property OFFCHIP_TERM NONE [get_ports leds[0]]
create_clock -period 83.333 -name clk -waveform {0.000 41.667} [get_ports clk]
create_generated_clock -name mck -source [get_pins channel1/ODDR_mck/C] -divide_by 1 [get_ports mck]
